version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    branches:
        only:
          - master
    steps:
      - run:
          command: echo "This job runs on only master branch"
