version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        user: root
    steps:
      - run:
          command: cat
      - run:
          command: |
            echo $VAR1
            echo $VAR2
